/**
 * Pure string renderers for everything a crawler or agent can fetch without
 * JavaScript: <head> metadata, static HTML content, Markdown twins, llms.txt,
 * sitemap, robots, the machine-readable catalog and the 404 bodies.
 *
 * Every page exists once per locale (src/i18n/locales.js): English at the
 * site root, the others under a two-letter prefix (/fr, /fr/worksheets/<slug>).
 * Static pages (About, Privacy, Terms) come from src/pages.js.
 *
 * No DOM, no React, no Node APIs: this file runs in the Vite config, the
 * prerender script, the Vercel edge middleware and in tests.
 */
import { WORKSHEETS, findWorksheetBySlug, findWorksheetById } from '../worksheets.js'
import { PAGES, findPageBySlug, findPageById } from '../pages.js'
import {
  SITE_URL, BRAND, AUTHOR, GITHUB_URL,
  LICENSE_URL, LICENSE_NAME, OG_IMAGE_PATH, THEME_COLOR, ACCENT_COLOR, OPERATOR, absoluteUrl,
} from './site.js'
import {
  t, interpolate, localizeWorksheet, localizedWorksheets, localizePage, localizedPages,
  LOCALES, LOCALE_META, DEFAULT_LOCALE, localePrefix, localizePath, splitLocale,
} from '../i18n/index.js'

export const HEAD_START = '<!-- seo:head -->'
export const HEAD_END = '<!-- /seo:head -->'
export const CONTENT_START = '<!-- seo:content -->'
export const CONTENT_END = '<!-- /seo:content -->'

/* ────────────────────────────── brand ────────────────────────────── */

/** Inline SVG of the brand icon (Tabler `ruler-2`, same as IconRuler2 in App.jsx). */
export function brandIcon(size = 24, extraAttrs = '') {
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false"${extraAttrs ? ` ${extraAttrs}` : ''}><path d="M17 3l4 4l-14 14l-4 -4l14 -14" /><path d="M16 7l-1.5 -1.5" /><path d="M13 10l-1.5 -1.5" /><path d="M10 13l-1.5 -1.5" /><path d="M7 16l-1.5 -1.5" /></svg>`
}

/* ────────────────────────────── routes ────────────────────────────── */

export function homeRoute(locale = DEFAULT_LOCALE) {
  if (locale === DEFAULT_LOCALE) {
    return { kind: 'home', locale, path: '/', md: '/index.md', html: 'index.html', mdFile: 'index.md' }
  }
  return { kind: 'home', locale, path: `/${locale}`, md: `/${locale}.md`, html: `${locale}.html`, mdFile: `${locale}.md` }
}

function localizedFiles(locale, rel) {
  const prefix = localePrefix(locale)
  const file = prefix ? `${locale}/${rel}` : rel
  return { path: `${prefix}/${rel}`, md: `${prefix}/${rel}.md`, html: `${file}.html`, mdFile: `${file}.md` }
}

export function worksheetRoute(ws, locale = DEFAULT_LOCALE) {
  const source = findWorksheetById(ws.id) ?? ws
  return {
    kind: 'worksheet',
    locale,
    worksheet: localizeWorksheet(source, locale),
    ...localizedFiles(locale, `worksheets/${source.slug}`),
  }
}

/** About / Privacy / Terms (src/pages.js), translated per locale. */
export function pageRoute(page, locale = DEFAULT_LOCALE) {
  const source = findPageById(page.id) ?? page
  return { kind: 'page', locale, page: localizePage(source, locale), ...localizedFiles(locale, source.slug) }
}

export function pageRoutes(locale = DEFAULT_LOCALE) {
  return PAGES.map(p => pageRoute(p, locale))
}

/** Open Graph preview image for a route; generated by `npm run og` (scripts/og-images.mjs). Shared by every locale; static pages reuse the home card. */
export function ogImagePath(route) {
  if (route.kind === 'worksheet') return `/og/${route.worksheet.slug}.png`
  return OG_IMAGE_PATH
}

export function ogImageAlt(route) {
  const { locale } = route
  if (route.kind === 'worksheet') return t(locale, 'seo.ogAltWorksheet', { label: route.worksheet.label, brand: BRAND })
  return t(locale, 'seo.ogAltHome', { brand: BRAND, tagline: t(locale, 'site.tagline') })
}

/** All routes (every locale, English first), or the routes of one locale. */
export function routes(locale) {
  const locales = locale ? [locale] : LOCALES
  return locales.flatMap(l => [homeRoute(l), ...WORKSHEETS.map(w => worksheetRoute(w, l)), ...pageRoutes(l)])
}

/** The same page in another locale. */
export function sameRouteIn(route, locale) {
  if (route.kind === 'home') return homeRoute(locale)
  if (route.kind === 'page') return pageRoute(route.page, locale)
  return worksheetRoute(route.worksheet, locale)
}

/** Normalise a pathname (strip trailing slash, collapse `/index` and `/index.html`). */
export function normalizePath(pathname) {
  let p = pathname || '/'
  try { p = decodeURIComponent(p) } catch { /* keep raw */ }
  if (p.length > 1) p = p.replace(/\/+$/, '')
  p = p.replace(/\/index(?:\.html)?$/, '')
  if (p === '') p = '/'
  return p
}

export function findRoute(pathname) {
  const { locale, rest } = splitLocale(normalizePath(pathname))
  if (rest === '/') return homeRoute(locale)
  const page = /^\/[a-z0-9-]+$/.test(rest) ? findPageBySlug(rest.slice(1)) : null
  if (page) return pageRoute(page, locale)
  const m = rest.match(/^\/worksheets\/([a-z0-9-]+)$/)
  if (m) {
    const ws = findWorksheetBySlug(m[1])
    return ws ? worksheetRoute(ws, locale) : null
  }
  return null
}

/* ────────────────────────────── helpers ────────────────────────────── */

export function escapeHtml(s) {
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

function attr(s) {
  return escapeHtml(s)
}

/** Mark a param as trusted HTML for `html()` (links, <code>, …). */
function raw(fragment) {
  return { __html: fragment }
}

/** Translate for HTML: escape the message template, then interpolate params (escaped unless wrapped with raw()). */
function html(locale, key, params = {}) {
  const safe = {}
  for (const [k, v] of Object.entries(params)) {
    safe[k] = v && typeof v === 'object' && '__html' in v ? v.__html : escapeHtml(String(v))
  }
  return interpolate(escapeHtml(t(locale, key)), safe)
}

/** Translate for Markdown / plain text. */
function text(locale, key, params = {}) {
  return interpolate(t(locale, key), params)
}

function code(s) {
  return raw(`<code>${escapeHtml(s)}</code>`)
}

function link(href, label) {
  return raw(`<a href="${attr(href)}">${escapeHtml(label)}</a>`)
}

const LINK_RE = /\[([^\]]+)\]\(([^)\s]+)\)/g

/** Plain text with optional `[label](url)` links → escaped HTML with anchors; site-relative links get the locale prefix. */
export function inlineHtml(text, locale = DEFAULT_LOCALE) {
  return escapeHtml(text).replace(LINK_RE, (_, label, href) => {
    const external = /^https?:\/\//.test(href)
    const target = href.startsWith('/') ? localizePath(href, locale) : href
    return `<a href="${target}"${external ? ' rel="noopener"' : ''}>${label}</a>`
  })
}

/** Same text for Markdown: site-relative links become absolute, locale-prefixed URLs. */
export function inlineMarkdown(text, locale = DEFAULT_LOCALE) {
  return text.replace(LINK_RE, (_, label, href) => `[${label}](${href.startsWith('/') ? absoluteUrl(localizePath(href, locale)) : href})`)
}

function jsonLd(obj) {
  // "</" must not appear inside a <script> element.
  return `<script type="application/ld+json">${JSON.stringify(obj).replace(/<\//g, '<\\/')}</script>`
}


function exampleLocalizedPath() {
  return `/fr/worksheets/${WORKSHEETS[0].slug}`
}

function langOf(locale) {
  return LOCALE_META[locale].lang
}

export function pageTitle(route) {
  const { locale } = route
  if (route.kind === 'home') return t(locale, 'seo.homeTitle', { brand: BRAND, tagline: t(locale, 'site.tagline') })
  if (route.kind === 'page') return `${route.page.title} · ${BRAND}`
  return t(locale, 'seo.worksheetTitle', { label: route.worksheet.label, brand: BRAND })
}

export function pageDescription(route) {
  const { locale } = route
  if (route.kind === 'home') return t(locale, 'site.description')
  if (route.kind === 'page') return route.page.description
  const ws = route.worksheet
  return t(locale, 'seo.worksheetDescription', {
    label: ws.label,
    labelLower: ws.label.toLowerCase(),
    grades: ws.grades,
    shortDesc: ws.shortDesc,
  })
}

const GRADE_AGES = { '1': '6-7', '2': '7-8', '3': '8-9' }

/** schema.org typicalAgeRange for a grade band like "2" or "1–3". Derived, not translated. */
export function agesForGrades(grades) {
  const parts = String(grades).split(/[–-]/).map(g => g.trim())
  const lo = GRADE_AGES[parts[0]]
  const hi = GRADE_AGES[parts[parts.length - 1]]
  if (!lo || !hi) return undefined
  return `${lo.split('-')[0]}-${hi.split('-')[1]}`
}

export function gradeLevelText(ws, locale) {
  return t(locale, ws.grades.includes('–') ? 'seo.gradeRange' : 'seo.gradeOne', { grades: ws.grades })
}

/* ────────────────────────────── JSON-LD ────────────────────────────── */

const AUTHOR_ID = `${SITE_URL}/#author`

function websiteId(locale) {
  return `${absoluteUrl(homeRoute(locale).path)}#website`
}

function authorNode() {
  return { '@type': 'Person', '@id': AUTHOR_ID, name: AUTHOR.name, url: AUTHOR.url }
}

function websiteNode(locale) {
  const home = absoluteUrl(homeRoute(locale).path)
  return {
    '@type': 'WebSite',
    '@id': websiteId(locale),
    url: locale === DEFAULT_LOCALE ? `${SITE_URL}/` : home,
    name: BRAND,
    alternateName: [t(locale, 'site.brandAlt'), pageTitle(homeRoute(locale))],
    description: t(locale, 'site.description'),
    inLanguage: langOf(locale),
    publisher: { '@id': AUTHOR_ID },
  }
}

export function structuredData(route) {
  const { locale } = route
  const lang = langOf(locale)
  const sheets = localizedWorksheets(locale)

  if (route.kind === 'home') {
    const home = locale === DEFAULT_LOCALE ? `${SITE_URL}/` : absoluteUrl(route.path)
    return {
      '@context': 'https://schema.org',
      '@graph': [
        websiteNode(locale),
        authorNode(),
        {
          '@type': 'WebApplication',
          '@id': `${home}#app`,
          name: BRAND,
          alternateName: t(locale, 'site.brandAlt'),
          url: home,
          description: t(locale, 'site.description'),
          applicationCategory: 'EducationalApplication',
          operatingSystem: 'Any (web browser)',
          browserRequirements: 'Requires JavaScript to generate and print worksheets',
          isAccessibleForFree: true,
          offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
          license: LICENSE_URL,
          author: { '@id': AUTHOR_ID },
          screenshot: absoluteUrl(OG_IMAGE_PATH),
          inLanguage: lang,
          featureList: sheets.map(w => t(locale, 'seo.featureItem', { label: w.label, shortDesc: w.shortDesc })),
          audience: { '@type': 'EducationalAudience', educationalRole: 'student' },
          isPartOf: { '@id': websiteId(locale) },
        },
        {
          '@type': 'ItemList',
          name: t(locale, 'seo.worksheetList', { brand: BRAND }),
          itemListElement: sheets.map((w, i) => ({
            '@type': 'ListItem',
            position: i + 1,
            name: w.label,
            url: absoluteUrl(worksheetRoute(w, locale).path),
          })),
        },
      ],
    }
  }

  if (route.kind === 'page') {
    const page = route.page
    return {
      '@context': 'https://schema.org',
      '@graph': [
        {
          '@type': 'WebPage',
          '@id': `${absoluteUrl(route.path)}#page`,
          url: absoluteUrl(route.path),
          name: pageTitle(route),
          description: pageDescription(route),
          isPartOf: { '@id': websiteId(locale) },
          inLanguage: lang,
          dateModified: page.updated,
          license: LICENSE_URL,
          author: { '@id': AUTHOR_ID },
        },
        authorNode(),
        breadcrumbs([{ name: BRAND, path: homeRoute(locale).path }, { name: page.navLabel, path: route.path }]),
      ],
    }
  }

  const ws = route.worksheet
  const url = absoluteUrl(route.path)
  return {
    '@context': 'https://schema.org',
    '@graph': [
      {
        '@type': 'LearningResource',
        '@id': `${url}#resource`,
        url,
        name: t(locale, 'seo.worksheetHeading', { label: ws.label }),
        alternateName: t(locale, 'seo.worksheetName', { brand: BRAND, label: ws.label }),
        description: ws.longDesc,
        learningResourceType: t(locale, ws.interactive ? 'seo.learningResourceInteractive' : 'seo.learningResourceWorksheet'),
        educationalLevel: gradeLevelText(ws, locale),
        typicalAgeRange: agesForGrades(ws.grades),
        teaches: ws.skills,
        educationalAlignment: ws.skills.map(skill => ({ '@type': 'AlignmentObject', alignmentType: 'teaches', targetName: skill })),
        educationalUse: 'practice',
        dateModified: ws.updated,
        audience: { '@type': 'EducationalAudience', educationalRole: 'student' },
        inLanguage: lang,
        isAccessibleForFree: true,
        license: LICENSE_URL,
        author: { '@id': AUTHOR_ID },
        isPartOf: { '@id': websiteId(locale) },
        encoding: [{ '@type': 'MediaObject', encodingFormat: 'text/markdown', contentUrl: absoluteUrl(route.md) }],
        image: absoluteUrl(ogImagePath(route)),
      },
      {
        '@type': 'FAQPage',
        '@id': `${url}#faq`,
        inLanguage: lang,
        isPartOf: { '@id': websiteId(locale) },
        mainEntity: ws.faq.map(item => ({
          '@type': 'Question',
          name: item.q,
          acceptedAnswer: { '@type': 'Answer', text: item.a },
        })),
      },
      authorNode(),
      breadcrumbs([{ name: BRAND, path: homeRoute(locale).path }, { name: ws.label, path: route.path }]),
    ],
  }
}

function breadcrumbs(items) {
  return {
    '@type': 'BreadcrumbList',
    itemListElement: items.map((it, i) => ({
      '@type': 'ListItem',
      position: i + 1,
      name: it.name,
      item: absoluteUrl(it.path),
    })),
  }
}

/* ────────────────────────────── <head> ────────────────────────────── */

function hreflangLinks(route) {
  const lines = LOCALES.map(l =>
    `<link rel="alternate" hreflang="${LOCALE_META[l].hreflang}" href="${attr(absoluteUrl(sameRouteIn(route, l).path))}" />`)
  lines.push(`<link rel="alternate" hreflang="x-default" href="${attr(absoluteUrl(sameRouteIn(route, DEFAULT_LOCALE).path))}" />`)
  return lines
}

export function renderHead(route) {
  const { locale } = route
  const title = pageTitle(route)
  const description = pageDescription(route)
  const url = absoluteUrl(route.path)
  const image = absoluteUrl(ogImagePath(route))
  const lines = [
    `<title>${escapeHtml(title)}</title>`,
    `<meta name="description" content="${attr(description)}" />`,
    `<meta name="robots" content="index, follow, max-image-preview:large" />`,
    `<meta name="theme-color" content="${THEME_COLOR}" />`,
    `<meta name="application-name" content="${BRAND}" />`,
    `<meta name="author" content="${attr(AUTHOR.name)}" />`,
    `<link rel="canonical" href="${attr(url)}" />`,
    ...hreflangLinks(route),
    `<link rel="alternate" type="text/markdown" href="${attr(absoluteUrl(route.md))}" title="${attr(title)} (Markdown)" />`,
    `<link rel="sitemap" type="application/xml" href="${attr(absoluteUrl('/sitemap.xml'))}" />`,
    `<meta property="og:type" content="website" />`,
    `<meta property="og:site_name" content="${BRAND}" />`,
    `<meta property="og:locale" content="${LOCALE_META[locale].og}" />`,
    ...LOCALES.filter(l => l !== locale).map(l => `<meta property="og:locale:alternate" content="${LOCALE_META[l].og}" />`),
    `<meta property="og:url" content="${attr(url)}" />`,
    `<meta property="og:title" content="${attr(title)}" />`,
    `<meta property="og:description" content="${attr(description)}" />`,
    `<meta property="og:image" content="${attr(image)}" />`,
    `<meta property="og:image:type" content="image/png" />`,
    `<meta property="og:image:width" content="1200" />`,
    `<meta property="og:image:height" content="630" />`,
    `<meta property="og:image:alt" content="${attr(ogImageAlt(route))}" />`,
    `<meta name="twitter:card" content="summary_large_image" />`,
    `<meta name="twitter:title" content="${attr(title)}" />`,
    `<meta name="twitter:description" content="${attr(description)}" />`,
    `<meta name="twitter:image" content="${attr(image)}" />`,
    `<meta name="twitter:image:alt" content="${attr(ogImageAlt(route))}" />`,
    jsonLd(structuredData(route)),
  ]
  return lines.join('\n    ')
}

/* ────────────────────────────── static HTML content ────────────────────────────── */

function worksheetCard(ws, locale) {
  const r = worksheetRoute(ws, locale)
  return (
    `<a class="catalog-card" href="${r.path}" style="--card-color:${ws.color}">` +
    `<span class="catalog-card-text"><span class="catalog-card-label">${escapeHtml(ws.label)}</span>` +
    `<span class="catalog-card-desc">${escapeHtml(ws.shortDesc)}</span></span></a>`
  )
}

function breadcrumbNav(locale, current) {
  return `<nav aria-label="Breadcrumb"><a href="${homeRoute(locale).path}">${BRAND}</a> › ${escapeHtml(current)}</nav>`
}

/**
 * Links shown in the site footer (React and static HTML share this list).
 * No GitHub link: the repository is going private.
 */
export function siteFooterLinks(locale = DEFAULT_LOCALE) {
  return [
    ...localizedPages(locale).map(p => ({ label: p.navLabel, path: pageRoute(p, locale).path, external: false })),
  ]
}

/** Site header for the crawlable HTML: brand link home and the About page (mirrors components/SiteHeader.jsx). */
export function headerHtml(locale = DEFAULT_LOCALE) {
  const about = localizedPages(locale).find(p => p.id === 'about')
  return `<header class="site-header no-print">
      <a class="site-brand" href="${homeRoute(locale).path}">${brandIcon(22)}<span>${BRAND}</span></a>
      <nav class="site-nav" aria-label="${attr(t(locale, 'static.footerSite'))}">
        <a class="site-nav-link" href="${pageRoute(about, locale).path}">${escapeHtml(about.navLabel)}</a>
      </nav>
    </header>`
}

export function footerHtml({ year = new Date().getFullYear(), locale = DEFAULT_LOCALE } = {}) {
  const links = siteFooterLinks(locale)
    .map(l => `<a href="${l.path}"${l.external ? ' rel="noopener noreferrer"' : ''}>${escapeHtml(l.label)}</a>`)
    .join('\n        ')
  return `<footer class="site-footer no-print">
      <nav class="site-footer-links" aria-label="${attr(t(locale, 'static.footerSite'))}">
        ${links}
      </nav>
      <p class="site-footer-legal">© ${year} ${escapeHtml(OPERATOR)} · <a href="${LICENSE_URL}" rel="license noopener">${LICENSE_NAME}</a></p>
    </footer>`
}

function homeContent(route) {
  const { locale } = route
  const h = (key, params) => html(locale, key, params)
  const cards = localizedWorksheets(locale).map(ws => worksheetCard(ws, locale)).join('\n        ')
  return `<main class="catalog catalog--full static-page">
      <header class="catalog-header">
        <div class="catalog-brand">
          <h1 class="catalog-title">${brandIcon(28)}${BRAND} – ${escapeHtml(t(locale, 'site.tagline'))}</h1>
          <p class="catalog-subtitle">${h('static.home.subtitle')}</p>
        </div>
      </header>
      <section class="static-intro">
        <p>${h('static.home.intro1', { brand: BRAND })}</p>
        <p>${h('static.home.intro2')}</p>
      </section>
      <h2>${h('static.home.worksheets')}</h2>
      <nav class="catalog-grid" aria-label="${attr(t(locale, 'static.worksheetTypes'))}">
        ${cards}
      </nav>
      <h2>${h('static.home.howItWorks')}</h2>
      <ol>
        <li>${h('static.home.step1')}</li>
        <li>${h('static.home.step2')}</li>
        <li>${h('static.home.step3')}</li>
      </ol>
      <h2>${h('static.home.audienceHeading')}</h2>
      <p>${h('static.home.audienceText', { brand: BRAND })}</p>
    </main>`
}

/**
 * Breadcrumb and page heading. Prerender-only: the React worksheet view has its
 * own compact topbar heading, so that the generator stays above the fold.
 */
function worksheetHeroHtml(route) {
  const { locale } = route
  const h = (key, params) => html(locale, key, params)
  const ws = route.worksheet
  return `${breadcrumbNav(locale, ws.label)}
      <header class="catalog-header">
        <div class="catalog-brand">
          <h1 class="catalog-title">${h('seo.worksheetHeading', { label: ws.label })}</h1>
          <p class="catalog-subtitle">${escapeHtml(ws.shortDesc)} · ${escapeHtml(gradeLevelText(ws, locale))}</p>
        </div>
      </header>`
}

/**
 * Everything below the heading: description, settings, how to use, sibling
 * worksheets and agent links. Shared with components/WorksheetDetails.jsx so the
 * crawlable fallback and the hydrated view cannot drift apart — the same
 * contract components/StaticPage.jsx has with staticBody().
 */
export function worksheetDetailsHtml(route) {
  const { locale } = route
  const h = (key, params) => html(locale, key, params)
  const ws = route.worksheet
  const others = localizedWorksheets(locale).filter(w => w.id !== ws.id)
  const settings = ws.settings.map(s => `<li>${escapeHtml(s)}</li>`).join('\n        ')
  const examples = ws.examples.map(e => `<li>${escapeHtml(e)}</li>`).join('\n        ')
  const faq = ws.faq.map(item => `<dt>${escapeHtml(item.q)}</dt>\n        <dd>${escapeHtml(item.a)}</dd>`).join('\n        ')
  const related = others.map(w => `<li><a href="${worksheetRoute(w, locale).path}">${escapeHtml(w.label)}</a> – ${escapeHtml(w.shortDesc)}</li>`).join('\n        ')
  return `<section class="static-intro">
        <p>${escapeHtml(ws.longDesc)}</p>
        <p><strong>${h('static.worksheet.skills')}:</strong> ${ws.skills.map(escapeHtml).join(', ')}. <strong>${h('static.worksheet.format')}:</strong> ${h(ws.interactive ? 'static.worksheet.formatInteractive' : 'static.worksheet.formatPrintable')}.</p>
      </section>
      ${fold(h('static.worksheet.settings'), `<ul>
        ${settings}
      </ul>`)}
      ${fold(h('static.worksheet.examples'), `<ul class="worksheet-examples">
        ${examples}
      </ul>`)}
      ${fold(h(ws.interactive ? 'static.worksheet.howToUseActivity' : 'static.worksheet.howToUseWorksheet'), `<ol>
        <li>${h('static.worksheet.step1', { url: link(route.path, absoluteUrl(route.path)) })}</li>
        <li>${h('static.worksheet.step2')}</li>
        <li>${h(ws.interactive ? 'static.worksheet.step3Interactive' : 'static.worksheet.step3Printable')}</li>
      </ol>`)}
      ${fold(h('static.worksheet.faq'), `<dl class="worksheet-faq">
        ${faq}
      </dl>`)}
      ${fold(h('static.worksheet.others', { brand: BRAND }), `<ul>
        ${related}
      </ul>`)}
`
}

/**
 * A collapsed section: the heading stays an <h2> inside the <summary>, so the
 * document outline and the heading-level invariant are unchanged, and the body
 * stays in the HTML for crawlers. Markdown twins are unaffected.
 */
function fold(heading, body) {
  return `<details class="static-fold">
        <summary><h2>${heading}</h2></summary>
        ${body}
      </details>`
}

function worksheetContent(route) {
  return `<main class="catalog catalog--full static-page">
      ${worksheetHeroHtml(route)}
      ${worksheetDetailsHtml(route)}
    </main>`
}

function formatDate(iso, locale = DEFAULT_LOCALE) {
  const d = new Date(`${iso}T00:00:00Z`)
  return d.toLocaleDateString(langOf(locale), { year: 'numeric', month: 'long', day: 'numeric', timeZone: 'UTC' })
}

function sectionHtml(section, locale) {
  const parts = [`<h2>${escapeHtml(section.heading)}</h2>`]
  for (const p of section.paragraphs || []) parts.push(`<p>${inlineHtml(p, locale)}</p>`)
  if (section.items?.length) {
    parts.push(`<ul>\n        ${section.items.map(i => `<li>${inlineHtml(i, locale)}</li>`).join('\n        ')}\n      </ul>`)
  }
  return parts.join('\n      ')
}

function pageBody(route) {
  const { locale, page } = route
  return `${breadcrumbNav(locale, page.navLabel)}
      <header class="catalog-header">
        <div class="catalog-brand">
          <h1 class="catalog-title">${escapeHtml(page.title)}</h1>
          <p class="catalog-subtitle">${html(locale, 'static.lastUpdated', { date: formatDate(page.updated, locale) })}</p>
        </div>
      </header>
      <section class="static-intro">
        <p>${inlineHtml(page.description, locale)}</p>
      </section>
      ${page.sections.map(s => sectionHtml(s, locale)).join('\n      ')}`
}

/**
 * Inner HTML of a non-worksheet page (about, privacy, terms):
 * used inside <main class="catalog catalog--full static-page"> both by the
 * prerendered fallback and by the React StaticPage component.
 */
export function staticBody(route) {
  if (route.kind === 'page') return pageBody(route)
  throw new Error(`staticBody: no static body for route kind "${route.kind}"`)
}

function staticMain(route) {
  return `<main class="catalog catalog--full static-page">
      ${staticBody(route)}
    </main>`
}

export function renderStaticContent(route) {
  const inner =
    route.kind === 'home' ? homeContent(route) :
    route.kind === 'worksheet' ? worksheetContent(route) :
    staticMain(route)
  return `<div id="static-content">\n    ${headerHtml(route.locale)}\n    ${inner}\n    ${footerHtml({ locale: route.locale })}\n    </div>`
}

/** Replace the marker blocks in an HTML template with this route's head and content, and set <html lang>. */
export function injectRoute(template, route) {
  const headRe = new RegExp(`${HEAD_START}[\\s\\S]*?${HEAD_END.replace('/', '\\/')}`)
  const contentRe = new RegExp(`${CONTENT_START}[\\s\\S]*?${CONTENT_END.replace('/', '\\/')}`)
  if (!headRe.test(template)) throw new Error('index.html is missing the <!-- seo:head --> … <!-- /seo:head --> markers')
  if (!contentRe.test(template)) throw new Error('index.html is missing the <!-- seo:content --> … <!-- /seo:content --> markers')
  return template
    .replace(/<html\b([^>]*)>/, (m, attrs) => `<html${attrs.replace(/\s+lang="[^"]*"/, '')} lang="${langOf(route.locale)}">`)
    .replace(headRe, () => `${HEAD_START}\n    ${renderHead(route)}\n    ${HEAD_END}`)
    .replace(contentRe, () => `${CONTENT_START}\n    ${renderStaticContent(route)}\n    ${CONTENT_END}`)
}

/* ────────────────────────────── Markdown ────────────────────────────── */

function mdLink(label, path) {
  return `[${label}](${absoluteUrl(path)})`
}

function agentLinksMarkdown(locale) {
  const m = (key, params) => text(locale, key, params)
  return [
    m('md.agentIntro'),
    ``,
    `- ${mdLink('llms.txt', '/llms.txt')}: ${m('md.llmsNote')}`,
    `- ${mdLink('worksheets.json', '/worksheets.json')}: ${m('md.catalogNote')}`,
    `- ${mdLink(m('md.sitemapLink'), '/sitemap.xml')}`,
  ].join('\n')
}

export function renderIndexMarkdown(route = homeRoute()) {
  const { locale } = route
  const m = (key, params) => text(locale, key, params)
  const list = localizedWorksheets(locale)
    .map(w => `- ${m('md.worksheetItem', { link: mdLink(w.label, worksheetRoute(w, locale).md), shortDesc: w.shortDesc, grades: w.grades })}`)
    .join('\n')
  return `# ${pageTitle(route)}

> ${m('site.description')}

${m('md.homeIntro', { brand: BRAND })}

## ${m('static.home.worksheets')}

${list}

## ${m('md.howItWorks')}

1. ${m('md.step1')}
2. ${m('md.step2')}
3. ${m('md.step3')}

## ${m('md.forDevelopers')}

${agentLinksMarkdown(locale)}
`
}

export function renderWorksheetMarkdown(route) {
  const { locale } = route
  const m = (key, params) => text(locale, key, params)
  const ws = route.worksheet
  const settings = ws.settings.map(s => `- ${s}`).join('\n')
  const examples = ws.examples.map(e => `- ${e}`).join('\n')
  const faqMd = ws.faq.map(item => `**${item.q}**\n\n${item.a}`).join('\n\n')
  const others = localizedWorksheets(locale).filter(w => w.id !== ws.id)
    .map(w => `- ${mdLink(w.label, worksheetRoute(w, locale).md)}: ${w.shortDesc}`)
    .join('\n')
  return `# ${m('seo.worksheetHeading', { label: ws.label })}

> ${ws.shortDesc}. ${gradeLevelText(ws, locale)}. ${m('static.worksheet.partOf', { link: mdLink(BRAND, homeRoute(locale).md) })}

${ws.longDesc}

**${m('static.worksheet.skills')}:** ${ws.skills.join(', ')}.
**${m('static.worksheet.format')}:** ${m(ws.interactive ? 'static.worksheet.formatInteractive' : 'static.worksheet.formatPrintable')}.
**${m('static.worksheet.url')}:** ${absoluteUrl(route.path)}
**${gradeLevelText(ws, locale)}** · ${m('md.lastUpdated')}: ${ws.updated}

## ${m('static.worksheet.settings')}

${settings}

## ${m('static.worksheet.examples')}

${examples}

## ${m('static.worksheet.faq')}

${faqMd}

## ${m('md.howToUse')}

1. ${m('md.wsStep1', { url: absoluteUrl(route.path) })}
2. ${m('md.wsStep2')}
3. ${m(ws.interactive ? 'static.worksheet.step3Interactive' : 'static.worksheet.step3Printable')}

## ${m('static.worksheet.others', { brand: BRAND })}

${others}

## ${m('md.forDevelopers')}

${agentLinksMarkdown(locale)}
`
}

function sectionMarkdown(section, locale) {
  const parts = [`## ${section.heading}`, '']
  for (const p of section.paragraphs || []) parts.push(inlineMarkdown(p, locale), '')
  if (section.items?.length) parts.push(...section.items.map(i => `- ${inlineMarkdown(i, locale)}`), '')
  return parts.join('\n').trimEnd()
}

export function renderPageMarkdown(route) {
  const { locale, page } = route
  const m = (key, params) => text(locale, key, params)
  const more = [
    { label: m('md.homeLink', { brand: BRAND }), md: homeRoute(locale).md },
    ...localizedPages(locale).filter(p => p.id !== page.id).map(p => ({ label: p.title, md: pageRoute(p, locale).md })),
  ].map(l => `- ${mdLink(l.label, l.md)}`).join('\n')
  return `# ${page.title}

> ${inlineMarkdown(page.description, locale)}

**${m('md.lastUpdated')}:** ${formatDate(page.updated, locale)}
**${m('static.worksheet.url')}:** ${absoluteUrl(route.path)}

${page.sections.map(s => sectionMarkdown(s, locale)).join('\n\n')}

## ${m('md.moreFrom', { brand: BRAND })}

${more}
`
}

export function renderMarkdown(route) {
  if (route.kind === 'home') return renderIndexMarkdown(route)
  if (route.kind === 'page') return renderPageMarkdown(route)
  return renderWorksheetMarkdown(route)
}

/* ────────────────────────────── llms.txt (English only) ────────────────────────────── */

/** Grade numbers a worksheet covers: "1–3" → [1, 2, 3]. */
function gradeNumbers(grades) {
  const parts = String(grades).split(/[–-]/).map(g => Number(g.trim()))
  if (parts.length === 1) return parts
  const out = []
  for (let g = parts[0]; g <= parts[parts.length - 1]; g++) out.push(g)
  return out
}

/**
 * A grade-band and skill index, generated from the catalog so it cannot drift.
 * This is what lets a model answer "which sheet for a 2nd grader learning
 * carrying?" from llms.txt alone, without fetching eight pages.
 */
function choosingBlock() {
  const byGrade = [1, 2, 3].map(g => {
    const matches = WORKSHEETS.filter(w => gradeNumbers(w.grades).includes(g))
    return `- Grade ${g} (ages ${GRADE_AGES[String(g)]}): ${matches.map(w => w.label).join(', ')}`
  }).join('\n')
  const bySkill = WORKSHEETS
    .map(w => `- ${w.label} (${absoluteUrl(worksheetRoute(w).path)}) teaches: ${w.skills.join(', ')}`)
    .join('\n')
  return `Choosing a worksheet — by grade:

${byGrade}

Choosing a worksheet — by skill:

${bySkill}`
}

/** How an AI answer should cite and reuse this site. */
function citationBlock() {
  return `Citation: ${BRAND} — ${SITE_URL}/ (operated by ${OPERATOR}). Licensed ${LICENSE_NAME}: attribution required, non-commercial use only. AI crawling and AI answers are explicitly permitted — see ${absoluteUrl('/robots.txt')}.
When recommending a worksheet, link the HTML page (${SITE_URL}/worksheets/<slug>), which carries the interactive generator; the .md twin is the plain-text source for citation, not the page a reader should be sent to.
Last updated: ${lastContentUpdate()}`
}

export function renderLlmsTxt() {
  const pages = PAGES.map(p => `- ${mdLink(p.title, pageRoute(p).md)}: ${p.description}`).join('\n')
  const worksheets = WORKSHEETS.map(w => {
    const after = w.nextSteps.map(id => findWorksheetById(id).label)
    const facts = [
      w.shortDesc,
      `${w.grades.includes('–') ? 'grades' : 'grade'} ${w.grades} (ages ${agesForGrades(w.grades)})`,
      w.interactive ? 'interactive on-screen activity, not printable' : 'printable, one A4/Letter page',
      `teaches ${w.skills.join(', ')}`,
      `settings: ${w.settings.map(setting => setting.split(':')[0].toLowerCase()).join(', ')}`,
      `example: ${w.examples[0]}`,
      ...(after.length ? [`next: ${after.join(', ')}`] : []),
    ]
    return `- ${mdLink(w.label, worksheetRoute(w).md)}: ${facts.join('; ')}`
  }).join('\n')
  const otherLocales = LOCALES.filter(l => l !== DEFAULT_LOCALE)
  const localized = otherLocales
    .map(l => `- ${mdLink(`Home page (${LOCALE_META[l].englishName})`, homeRoute(l).md)}: ${t(DEFAULT_LOCALE, 'llms.optionalLocale', { language: LOCALE_META[l].englishName })}`)
    .join('\n')
  return `# ${BRAND}

> ${BRAND} (“${t(DEFAULT_LOCALE, 'site.brandAlt')}”) is a free, open-source web app with printable, randomized math worksheets for grades 1–3: multiplication tables, addition and subtraction, column addition, long multiplication, comparison, rounding, number patterns, plus an interactive equation explorer. Site: ${SITE_URL}/

Worksheets are generated in the browser and printed from the print dialog; there is no account, no server API and no cost (${LICENSE_NAME}). Every HTML page has a Markdown twin: append \`.md\` to the path or request the page with \`Accept: text/markdown\`. Pages are also available in ${otherLocales.map(l => LOCALE_META[l].englishName).join(', ')} under a two-letter path prefix: insert the two-letter code after the origin, for example \`${exampleLocalizedPath()}\`.

${choosingBlock()}

${citationBlock()}

## Worksheets

${worksheets}

## Developers

- ${mdLink('Worksheet catalog (JSON)', '/worksheets.json')}: ids, slugs, URLs, grades, skills and settings for every worksheet
- [Source on GitHub](${GITHUB_URL}): React 19 + Vite, ${LICENSE_NAME}

## Optional

- ${mdLink('Home page (Markdown)', '/index.md')}: overview of the site
- ${mdLink('llms-full.txt', '/llms-full.txt')}: every page's Markdown concatenated in one file
- ${mdLink('Sitemap', '/sitemap.xml')}: all HTML URLs in every language
${pages}
${localized}
`
}

export function renderLlmsFullTxt() {
  const routeList = routes(DEFAULT_LOCALE)
  const sections = routeList.map(r => renderMarkdown(r).trimEnd())
  const otherLocales = LOCALES.filter(l => l !== DEFAULT_LOCALE)
  // Deliberately headingless: a `# ` line here would break the invariant that
  // this file contains exactly one H1 per route.
  const preamble = `${BRAND} — full site content (English)

> Every English page of ${BRAND} concatenated as Markdown, in sitemap order, separated by \`---\`.

Site: ${SITE_URL}/ · Last updated: ${lastContentUpdate()} · License: ${LICENSE_NAME} (attribution required, non-commercial)
Contents: ${routeList.map(r => pageTitle(r).split(' · ')[0]).join(' · ')}

${choosingBlock()}

${citationBlock()}

Languages: this file is English only. The same pages exist in ${otherLocales.map(l => LOCALE_META[l].englishName).join(', ')} under a two-letter path prefix inserted after the origin — \`${exampleLocalizedPath()}\`. Structured catalog: ${absoluteUrl('/worksheets.json')}`
  return `${[preamble, ...sections].join('\n\n---\n\n')}\n`
}

/* ────────────────────────────── sitemap / robots / catalog ────────────────────────────── */

export function renderSitemap({ now = new Date() } = {}) {
  const lastmod = now.toISOString().slice(0, 10)
  const urls = routes().map(r => {
    const priority = r.kind === 'home' ? '1.0' : r.kind === 'worksheet' ? '0.8' : r.kind === 'page' ? '0.3' : '0.5'
    const modified = r.worksheet?.updated || r.page?.updated || lastmod
    const alternates = [
      ...LOCALES.map(l => `    <xhtml:link rel="alternate" hreflang="${LOCALE_META[l].hreflang}" href="${escapeHtml(absoluteUrl(sameRouteIn(r, l).path))}" />`),
      `    <xhtml:link rel="alternate" hreflang="x-default" href="${escapeHtml(absoluteUrl(sameRouteIn(r, DEFAULT_LOCALE).path))}" />`,
    ].join('\n')
    return `  <url>
    <loc>${escapeHtml(absoluteUrl(r.path))}</loc>
    <lastmod>${modified}</lastmod>
    <changefreq>monthly</changefreq>
    <priority>${priority}</priority>
${alternates}
  </url>`
  })
  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">
${urls.join('\n')}
</urlset>
`
}

export const AI_CRAWLERS = [
  'GPTBot', 'OAI-SearchBot', 'ChatGPT-User', 'ClaudeBot', 'Claude-Web', 'Claude-SearchBot', 'anthropic-ai',
  'PerplexityBot', 'Perplexity-User', 'Google-Extended', 'Applebot-Extended', 'CCBot', 'Bytespider', 'Amazonbot', 'meta-externalagent',
]

export function renderRobots() {
  const blocks = AI_CRAWLERS.map(ua => `User-agent: ${ua}\nAllow: /`).join('\n\n')
  return `# ${BRAND} – ${SITE_URL}/
# Everything is public. AI crawlers and answer engines are welcome; see /llms.txt.

User-agent: *
Allow: /

${blocks}

Sitemap: ${absoluteUrl('/sitemap.xml')}
`
}

function catalogRef(id) {
  const w = findWorksheetById(id)
  return { id: w.id, label: w.label, url: absoluteUrl(worksheetRoute(w).path) }
}

/** Newest content date across the catalog and the static pages. */
export function lastContentUpdate() {
  return [...WORKSHEETS.map(w => w.updated), ...PAGES.map(p => p.updated)].sort().pop()
}

export function catalogJson({ now = new Date() } = {}) {
  return {
    schemaVersion: 1,
    name: BRAND,
    alternateName: t(DEFAULT_LOCALE, 'site.brandAlt'),
    description: t(DEFAULT_LOCALE, 'site.description'),
    url: `${SITE_URL}/`,
    generatedAt: now.toISOString(),
    lastUpdated: lastContentUpdate(),
    license: { name: LICENSE_NAME, url: LICENSE_URL },
    repository: GITHUB_URL,
    llms: absoluteUrl('/llms.txt'),
    llmsFull: absoluteUrl('/llms-full.txt'),
    robots: absoluteUrl('/robots.txt'),
    sitemap: absoluteUrl('/sitemap.xml'),
    usage: {
      license: { name: LICENSE_NAME, url: LICENSE_URL },
      attribution: `${BRAND} — ${SITE_URL}/`,
      operator: OPERATOR,
      commercialUse: false,
      aiCrawlingAllowed: true,
      aiAnswersAllowed: true,
      citeUrl: "a worksheet's `url`, not its `markdownUrl`: the page carries the generator",
      requiresJavaScript: true,
      printFormat: 'A4 or US Letter, one page',
    },
    pages: Object.fromEntries(PAGES.map(p => [p.id, absoluteUrl(pageRoute(p).path)])),
    locales: LOCALES.map(l => ({ code: l, lang: LOCALE_META[l].lang, name: LOCALE_META[l].englishName, url: absoluteUrl(homeRoute(l).path) })),
    worksheets: WORKSHEETS.map(w => {
      const r = worksheetRoute(w)
      return {
        id: w.id,
        slug: w.slug,
        label: w.label,
        url: absoluteUrl(r.path),
        markdownUrl: absoluteUrl(r.md),
        alternates: Object.fromEntries(LOCALES.map(l => [l, absoluteUrl(worksheetRoute(w, l).path)])),
        description: w.shortDesc,
        longDescription: w.longDesc,
        grades: w.grades,
        typicalAgeRange: agesForGrades(w.grades),
        skills: w.skills,
        settings: w.settings,
        examples: w.examples,
        faq: w.faq,
        prerequisites: w.prerequisites.map(id => catalogRef(id)),
        nextSteps: w.nextSteps.map(id => catalogRef(id)),
        updated: w.updated,
        printable: !w.interactive,
        interactive: w.interactive,
      }
    }),
  }
}

export function renderCatalogJson(opts) {
  return `${JSON.stringify(catalogJson(opts), null, 2)}\n`
}

/* ────────────────────────────── 404 ────────────────────────────── */

function notFoundLinks(locale) {
  return [
    { label: t(locale, 'notFound.home', { brand: BRAND }), path: homeRoute(locale).path },
    ...localizedWorksheets(locale).map(w => ({ label: t(locale, 'notFound.worksheet', { label: w.label }), path: worksheetRoute(w, locale).path })),
    ...localizedPages(locale).map(p => ({ label: p.title, path: pageRoute(p, locale).path })),
    { label: t(locale, 'notFound.sitemap'), path: '/sitemap.xml' },
    { label: t(locale, 'notFound.llms'), path: '/llms.txt' },
    { label: t(locale, 'notFound.catalog'), path: '/worksheets.json' },
  ]
}

export function renderNotFoundMarkdown(pathname = '', locale = DEFAULT_LOCALE) {
  const m = (key, params) => text(locale, key, params)
  const shown = pathname ? `\`${pathname.replace(/`/g, '')}\` ` : ''
  const links = notFoundLinks(locale).map(l => `- ${mdLink(l.label, l.path)}`).join('\n')
  return `# ${m('notFound.title')} · ${BRAND}

${m('notFound.body', { path: shown, site: SITE_URL })}

## ${m('notFound.whereNext')}

${links}

${m('notFound.twinMd')}
`
}

export function renderNotFoundHtml(pathname = '', locale = DEFAULT_LOCALE) {
  const h = (key, params) => html(locale, key, params)
  const links = notFoundLinks(locale).map(l => `<li><a href="${l.path}">${escapeHtml(l.label)}</a></li>`).join('\n        ')
  const shown = pathname ? raw(`<code>${escapeHtml(pathname)}</code> `) : ''
  return `<!doctype html>
<html lang="${langOf(locale)}">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="robots" content="noindex" />
    <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
    <title>${h('notFound.title')} · ${BRAND}</title>
    <style>
      body { margin: 0; padding: 48px 20px; font-family: Inter, system-ui, -apple-system, "Segoe UI", sans-serif; color: #1f2937; background: #f5f5f0; }
      main { max-width: 640px; margin: 0 auto; }
      h1 { font-size: 26px; margin: 0 0 8px; }
      h2 { font-size: 18px; margin: 28px 0 8px; }
      a { color: ${ACCENT_COLOR}; }
      code { background: #e5e7eb; padding: 1px 5px; border-radius: 4px; }
      ul { padding-left: 20px; line-height: 1.7; }
    </style>
  </head>
  <body>
    <main>
      <h1>${h('notFound.title')}</h1>
      <p>${h('notFound.body', { path: shown, site: BRAND })}</p>
      <h2>${h('notFound.whereNext')}</h2>
      <ul>
        ${links}
      </ul>
      <p>${h('notFound.twinHtml', { code: code('.md'), accept: code('Accept: text/markdown') })}</p>
    </main>
  </body>
</html>
`
}

/* ────────────────────────────── build output ────────────────────────────── */

/**
 * Everything the prerender step writes into dist/, keyed by relative path.
 * @param {string} template  the built dist/index.html
 */
export function buildSiteFiles(template, { now = new Date() } = {}) {
  const files = {}
  for (const route of routes()) {
    files[route.html] = injectRoute(template, route)
    files[route.mdFile] = renderMarkdown(route)
  }
  files['llms.txt'] = renderLlmsTxt()
  files['llms-full.txt'] = renderLlmsFullTxt()
  files['sitemap.xml'] = renderSitemap({ now })
  files['robots.txt'] = renderRobots()
  files['worksheets.json'] = renderCatalogJson({ now })
  files['404.html'] = renderNotFoundHtml()
  return files
}
