/**
 * Pure string renderers for everything a crawler or agent can fetch without
 * JavaScript: <head> metadata, static HTML content, Markdown twins, llms.txt,
 * sitemap, robots, the machine-readable catalog and the 404 bodies.
 *
 * Every page exists once per locale (src/i18n/locales.js): English at the
 * site root, the others under a two-letter prefix (/fr, /fr/worksheets/<slug>).
 * Static pages (About, Privacy, Terms) come from src/pages.js.
 *
 * No DOM, no React, no Node APIs: this file runs in the Vite config, the
 * prerender script, the Vercel edge middleware and in tests.
 */
import { WORKSHEETS, findWorksheetBySlug, findWorksheetById } from '../worksheets.js'
import { PAGES, findPageBySlug, findPageById } from '../pages.js'
import {
  SITE_URL, BRAND, AUTHOR, GITHUB_URL,
  LICENSE_URL, LICENSE_NAME, OG_IMAGE_PATH, THEME_COLOR, OPERATOR, absoluteUrl,
} from './site.js'
import {
  t, interpolate, localizeWorksheet, localizedWorksheets, localizePage, localizedPages,
  LOCALES, LOCALE_META, DEFAULT_LOCALE, localePrefix, localizePath, splitLocale,
} from '../i18n/index.js'

export const HEAD_START = '<!-- seo:head -->'
export const HEAD_END = '<!-- /seo:head -->'
export const CONTENT_START = '<!-- seo:content -->'
export const CONTENT_END = '<!-- /seo:content -->'

/* ────────────────────────────── brand ────────────────────────────── */

/** Inline SVG of the brand icon (Tabler `ruler-2`, same as IconRuler2 in App.jsx). */
export function brandIcon(size = 24, extraAttrs = '') {
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false"${extraAttrs ? ` ${extraAttrs}` : ''}><path d="M17 3l4 4l-14 14l-4 -4l14 -14" /><path d="M16 7l-1.5 -1.5" /><path d="M13 10l-1.5 -1.5" /><path d="M10 13l-1.5 -1.5" /><path d="M7 16l-1.5 -1.5" /></svg>`
}

/* ────────────────────────────── routes ────────────────────────────── */

export function homeRoute(locale = DEFAULT_LOCALE) {
  if (locale === DEFAULT_LOCALE) {
    return { kind: 'home', locale, path: '/', md: '/index.md', html: 'index.html', mdFile: 'index.md' }
  }
  return { kind: 'home', locale, path: `/${locale}`, md: `/${locale}.md`, html: `${locale}.html`, mdFile: `${locale}.md` }
}

function localizedFiles(locale, rel) {
  const prefix = localePrefix(locale)
  const file = prefix ? `${locale}/${rel}` : rel
  return { path: `${prefix}/${rel}`, md: `${prefix}/${rel}.md`, html: `${file}.html`, mdFile: `${file}.md` }
}

export function worksheetRoute(ws, locale = DEFAULT_LOCALE) {
  const source = findWorksheetById(ws.id) ?? ws
  return {
    kind: 'worksheet',
    locale,
    worksheet: localizeWorksheet(source, locale),
    ...localizedFiles(locale, `worksheets/${source.slug}`),
  }
}

export function developersRoute(locale = DEFAULT_LOCALE) {
  return { kind: 'developers', locale, ...localizedFiles(locale, 'developers') }
}

/** About / Privacy / Terms (src/pages.js), translated per locale. */
export function pageRoute(page, locale = DEFAULT_LOCALE) {
  const source = findPageById(page.id) ?? page
  return { kind: 'page', locale, page: localizePage(source, locale), ...localizedFiles(locale, source.slug) }
}

export function pageRoutes(locale = DEFAULT_LOCALE) {
  return PAGES.map(p => pageRoute(p, locale))
}

/** Open Graph preview image for a route; generated by `npm run og` (scripts/og-images.mjs). Shared by every locale; static pages reuse the home card. */
export function ogImagePath(route) {
  if (route.kind === 'worksheet') return `/og/${route.worksheet.slug}.png`
  if (route.kind === 'developers') return '/og/developers.png'
  return OG_IMAGE_PATH
}

export function ogImageAlt(route) {
  const { locale } = route
  if (route.kind === 'worksheet') return t(locale, 'seo.ogAltWorksheet', { label: route.worksheet.label, brand: BRAND })
  if (route.kind === 'developers') return t(locale, 'seo.ogAltDevelopers', { brand: BRAND })
  return t(locale, 'seo.ogAltHome', { brand: BRAND, tagline: t(locale, 'site.tagline') })
}

/** All routes (every locale, English first), or the routes of one locale. */
export function routes(locale) {
  const locales = locale ? [locale] : LOCALES
  return locales.flatMap(l => [homeRoute(l), ...WORKSHEETS.map(w => worksheetRoute(w, l)), developersRoute(l), ...pageRoutes(l)])
}

/** The same page in another locale. */
export function sameRouteIn(route, locale) {
  if (route.kind === 'home') return homeRoute(locale)
  if (route.kind === 'developers') return developersRoute(locale)
  if (route.kind === 'page') return pageRoute(route.page, locale)
  return worksheetRoute(route.worksheet, locale)
}

/** Normalise a pathname (strip trailing slash, collapse `/index` and `/index.html`). */
export function normalizePath(pathname) {
  let p = pathname || '/'
  try { p = decodeURIComponent(p) } catch { /* keep raw */ }
  if (p.length > 1) p = p.replace(/\/+$/, '')
  p = p.replace(/\/index(?:\.html)?$/, '')
  if (p === '') p = '/'
  return p
}

export function findRoute(pathname) {
  const { locale, rest } = splitLocale(normalizePath(pathname))
  if (rest === '/') return homeRoute(locale)
  if (rest === '/developers') return developersRoute(locale)
  const page = /^\/[a-z0-9-]+$/.test(rest) ? findPageBySlug(rest.slice(1)) : null
  if (page) return pageRoute(page, locale)
  const m = rest.match(/^\/worksheets\/([a-z0-9-]+)$/)
  if (m) {
    const ws = findWorksheetBySlug(m[1])
    return ws ? worksheetRoute(ws, locale) : null
  }
  return null
}

/* ────────────────────────────── helpers ────────────────────────────── */

export function escapeHtml(s) {
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

function attr(s) {
  return escapeHtml(s)
}

/** Mark a param as trusted HTML for `html()` (links, <code>, …). */
function raw(fragment) {
  return { __html: fragment }
}

/** Translate for HTML: escape the message template, then interpolate params (escaped unless wrapped with raw()). */
function html(locale, key, params = {}) {
  const safe = {}
  for (const [k, v] of Object.entries(params)) {
    safe[k] = v && typeof v === 'object' && '__html' in v ? v.__html : escapeHtml(String(v))
  }
  return interpolate(escapeHtml(t(locale, key)), safe)
}

/** Translate for Markdown / plain text. */
function text(locale, key, params = {}) {
  return interpolate(t(locale, key), params)
}

function code(s) {
  return raw(`<code>${escapeHtml(s)}</code>`)
}

function link(href, label) {
  return raw(`<a href="${attr(href)}">${escapeHtml(label)}</a>`)
}

const LINK_RE = /\[([^\]]+)\]\(([^)\s]+)\)/g

/** Plain text with optional `[label](url)` links → escaped HTML with anchors; site-relative links get the locale prefix. */
export function inlineHtml(text, locale = DEFAULT_LOCALE) {
  return escapeHtml(text).replace(LINK_RE, (_, label, href) => {
    const external = /^https?:\/\//.test(href)
    const target = href.startsWith('/') ? localizePath(href, locale) : href
    return `<a href="${target}"${external ? ' rel="noopener"' : ''}>${label}</a>`
  })
}

/** Same text for Markdown: site-relative links become absolute, locale-prefixed URLs. */
export function inlineMarkdown(text, locale = DEFAULT_LOCALE) {
  return text.replace(LINK_RE, (_, label, href) => `[${label}](${href.startsWith('/') ? absoluteUrl(localizePath(href, locale)) : href})`)
}

function jsonLd(obj) {
  // "</" must not appear inside a <script> element.
  return `<script type="application/ld+json">${JSON.stringify(obj).replace(/<\//g, '<\\/')}</script>`
}

function languageNames() {
  return LOCALES.filter(l => l !== DEFAULT_LOCALE).map(l => LOCALE_META[l].name).join(', ')
}

function exampleLocalizedPath() {
  return `/fr/worksheets/${WORKSHEETS[0].slug}`
}

function langOf(locale) {
  return LOCALE_META[locale].lang
}

export function pageTitle(route) {
  const { locale } = route
  if (route.kind === 'home') return t(locale, 'seo.homeTitle', { brand: BRAND, tagline: t(locale, 'site.tagline') })
  if (route.kind === 'developers') return t(locale, 'seo.developersTitle', { brand: BRAND })
  if (route.kind === 'page') return `${route.page.title} · ${BRAND}`
  return t(locale, 'seo.worksheetTitle', { label: route.worksheet.label, brand: BRAND })
}

export function pageDescription(route) {
  const { locale } = route
  if (route.kind === 'home') return t(locale, 'site.description')
  if (route.kind === 'developers') return t(locale, 'seo.developersDescription', { brand: BRAND })
  if (route.kind === 'page') return route.page.description
  const ws = route.worksheet
  return t(locale, 'seo.worksheetDescription', {
    label: ws.label,
    labelLower: ws.label.toLowerCase(),
    grades: ws.grades,
    shortDesc: ws.shortDesc,
  })
}

function gradeLevelText(ws, locale) {
  return t(locale, ws.grades.includes('–') ? 'seo.gradeRange' : 'seo.gradeOne', { grades: ws.grades })
}

/* ────────────────────────────── JSON-LD ────────────────────────────── */

const AUTHOR_ID = `${SITE_URL}/#author`

function websiteId(locale) {
  return `${absoluteUrl(homeRoute(locale).path)}#website`
}

function authorNode() {
  return { '@type': 'Person', '@id': AUTHOR_ID, name: AUTHOR.name, url: AUTHOR.url }
}

function websiteNode(locale) {
  const home = absoluteUrl(homeRoute(locale).path)
  return {
    '@type': 'WebSite',
    '@id': websiteId(locale),
    url: locale === DEFAULT_LOCALE ? `${SITE_URL}/` : home,
    name: BRAND,
    alternateName: [t(locale, 'site.brandAlt'), pageTitle(homeRoute(locale))],
    description: t(locale, 'site.description'),
    inLanguage: langOf(locale),
    publisher: { '@id': AUTHOR_ID },
  }
}

export function structuredData(route) {
  const { locale } = route
  const lang = langOf(locale)
  const sheets = localizedWorksheets(locale)

  if (route.kind === 'home') {
    const home = locale === DEFAULT_LOCALE ? `${SITE_URL}/` : absoluteUrl(route.path)
    return {
      '@context': 'https://schema.org',
      '@graph': [
        websiteNode(locale),
        authorNode(),
        {
          '@type': 'WebApplication',
          '@id': `${home}#app`,
          name: BRAND,
          alternateName: t(locale, 'site.brandAlt'),
          url: home,
          description: t(locale, 'site.description'),
          applicationCategory: 'EducationalApplication',
          operatingSystem: 'Any (web browser)',
          browserRequirements: 'Requires JavaScript to generate and print worksheets',
          isAccessibleForFree: true,
          offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
          license: LICENSE_URL,
          author: { '@id': AUTHOR_ID },
          screenshot: absoluteUrl(OG_IMAGE_PATH),
          inLanguage: lang,
          featureList: sheets.map(w => t(locale, 'seo.featureItem', { label: w.label, shortDesc: w.shortDesc })),
          audience: { '@type': 'EducationalAudience', educationalRole: 'student' },
          isPartOf: { '@id': websiteId(locale) },
        },
        {
          '@type': 'ItemList',
          name: t(locale, 'seo.worksheetList', { brand: BRAND }),
          itemListElement: sheets.map((w, i) => ({
            '@type': 'ListItem',
            position: i + 1,
            name: w.label,
            url: absoluteUrl(worksheetRoute(w, locale).path),
          })),
        },
      ],
    }
  }

  if (route.kind === 'developers') {
    return {
      '@context': 'https://schema.org',
      '@graph': [
        {
          '@type': 'WebPage',
          '@id': `${absoluteUrl(route.path)}#page`,
          url: absoluteUrl(route.path),
          name: pageTitle(route),
          description: pageDescription(route),
          isPartOf: { '@id': websiteId(locale) },
          inLanguage: lang,
          about: {
            '@type': 'SoftwareSourceCode',
            name: BRAND,
            codeRepository: GITHUB_URL,
            programmingLanguage: 'JavaScript',
            runtimePlatform: 'React 19, Vite',
            license: LICENSE_URL,
            author: { '@id': AUTHOR_ID },
          },
        },
        authorNode(),
        breadcrumbs([
          { name: BRAND, path: homeRoute(locale).path },
          { name: t(locale, 'seo.developersCrumb'), path: route.path },
        ]),
      ],
    }
  }

  if (route.kind === 'page') {
    const page = route.page
    return {
      '@context': 'https://schema.org',
      '@graph': [
        {
          '@type': 'WebPage',
          '@id': `${absoluteUrl(route.path)}#page`,
          url: absoluteUrl(route.path),
          name: pageTitle(route),
          description: pageDescription(route),
          isPartOf: { '@id': websiteId(locale) },
          inLanguage: lang,
          dateModified: page.updated,
          license: LICENSE_URL,
          author: { '@id': AUTHOR_ID },
        },
        authorNode(),
        breadcrumbs([{ name: BRAND, path: homeRoute(locale).path }, { name: page.navLabel, path: route.path }]),
      ],
    }
  }

  const ws = route.worksheet
  const url = absoluteUrl(route.path)
  return {
    '@context': 'https://schema.org',
    '@graph': [
      {
        '@type': 'LearningResource',
        '@id': `${url}#resource`,
        url,
        name: t(locale, 'seo.worksheetHeading', { label: ws.label }),
        alternateName: t(locale, 'seo.worksheetName', { brand: BRAND, label: ws.label }),
        description: ws.longDesc,
        learningResourceType: t(locale, ws.interactive ? 'seo.learningResourceInteractive' : 'seo.learningResourceWorksheet'),
        educationalLevel: gradeLevelText(ws, locale),
        teaches: ws.skills,
        educationalUse: 'practice',
        audience: { '@type': 'EducationalAudience', educationalRole: 'student' },
        inLanguage: lang,
        isAccessibleForFree: true,
        license: LICENSE_URL,
        author: { '@id': AUTHOR_ID },
        isPartOf: { '@id': websiteId(locale) },
        encoding: [{ '@type': 'MediaObject', encodingFormat: 'text/markdown', contentUrl: absoluteUrl(route.md) }],
        image: absoluteUrl(ogImagePath(route)),
      },
      authorNode(),
      breadcrumbs([{ name: BRAND, path: homeRoute(locale).path }, { name: ws.label, path: route.path }]),
    ],
  }
}

function breadcrumbs(items) {
  return {
    '@type': 'BreadcrumbList',
    itemListElement: items.map((it, i) => ({
      '@type': 'ListItem',
      position: i + 1,
      name: it.name,
      item: absoluteUrl(it.path),
    })),
  }
}

/* ────────────────────────────── <head> ────────────────────────────── */

function hreflangLinks(route) {
  const lines = LOCALES.map(l =>
    `<link rel="alternate" hreflang="${LOCALE_META[l].hreflang}" href="${attr(absoluteUrl(sameRouteIn(route, l).path))}" />`)
  lines.push(`<link rel="alternate" hreflang="x-default" href="${attr(absoluteUrl(sameRouteIn(route, DEFAULT_LOCALE).path))}" />`)
  return lines
}

export function renderHead(route) {
  const { locale } = route
  const title = pageTitle(route)
  const description = pageDescription(route)
  const url = absoluteUrl(route.path)
  const image = absoluteUrl(ogImagePath(route))
  const lines = [
    `<title>${escapeHtml(title)}</title>`,
    `<meta name="description" content="${attr(description)}" />`,
    `<meta name="robots" content="index, follow, max-image-preview:large" />`,
    `<meta name="theme-color" content="${THEME_COLOR}" />`,
    `<meta name="application-name" content="${BRAND}" />`,
    `<meta name="author" content="${attr(AUTHOR.name)}" />`,
    `<link rel="canonical" href="${attr(url)}" />`,
    ...hreflangLinks(route),
    `<link rel="alternate" type="text/markdown" href="${attr(absoluteUrl(route.md))}" title="${attr(title)} (Markdown)" />`,
    `<link rel="sitemap" type="application/xml" href="${attr(absoluteUrl('/sitemap.xml'))}" />`,
    `<meta property="og:type" content="website" />`,
    `<meta property="og:site_name" content="${BRAND}" />`,
    `<meta property="og:locale" content="${LOCALE_META[locale].og}" />`,
    ...LOCALES.filter(l => l !== locale).map(l => `<meta property="og:locale:alternate" content="${LOCALE_META[l].og}" />`),
    `<meta property="og:url" content="${attr(url)}" />`,
    `<meta property="og:title" content="${attr(title)}" />`,
    `<meta property="og:description" content="${attr(description)}" />`,
    `<meta property="og:image" content="${attr(image)}" />`,
    `<meta property="og:image:type" content="image/png" />`,
    `<meta property="og:image:width" content="1200" />`,
    `<meta property="og:image:height" content="630" />`,
    `<meta property="og:image:alt" content="${attr(ogImageAlt(route))}" />`,
    `<meta name="twitter:card" content="summary_large_image" />`,
    `<meta name="twitter:title" content="${attr(title)}" />`,
    `<meta name="twitter:description" content="${attr(description)}" />`,
    `<meta name="twitter:image" content="${attr(image)}" />`,
    `<meta name="twitter:image:alt" content="${attr(ogImageAlt(route))}" />`,
    jsonLd(structuredData(route)),
  ]
  return lines.join('\n    ')
}

/* ────────────────────────────── static HTML content ────────────────────────────── */

function worksheetCard(ws, locale) {
  const r = worksheetRoute(ws, locale)
  return (
    `<a class="catalog-card" href="${r.path}" style="--card-color:${ws.color}">` +
    `<span class="catalog-card-text"><span class="catalog-card-label">${escapeHtml(ws.label)}</span>` +
    `<span class="catalog-card-desc">${escapeHtml(ws.shortDesc)}</span></span></a>`
  )
}

function agentLinksHtml(locale) {
  return `<p>${html(locale, 'static.agentLinks.text', {
    code: code('.md'),
    accept: code('Accept: text/markdown'),
    llms: link('/llms.txt', t(locale, 'static.agentLinks.llms')),
    catalog: link('/worksheets.json', t(locale, 'static.agentLinks.catalog')),
    sitemap: link('/sitemap.xml', t(locale, 'static.agentLinks.sitemap')),
    developers: link(developersRoute(locale).path, t(locale, 'static.agentLinks.developers')),
    github: link(GITHUB_URL, t(locale, 'static.agentLinks.github')),
    license: LICENSE_NAME,
  })}</p>`
}

function breadcrumbNav(locale, current) {
  return `<nav aria-label="Breadcrumb"><a href="${homeRoute(locale).path}">${BRAND}</a> › ${escapeHtml(current)}</nav>`
}

/** Links shown in the site footer (React and static HTML share this list). */
export function siteFooterLinks(locale = DEFAULT_LOCALE) {
  return [
    ...localizedPages(locale).map(p => ({ label: p.navLabel, path: pageRoute(p, locale).path, external: false })),
    { label: 'GitHub', path: GITHUB_URL, external: true },
  ]
}

export function footerHtml({ year = new Date().getFullYear(), locale = DEFAULT_LOCALE } = {}) {
  const links = siteFooterLinks(locale)
    .map(l => `<a href="${l.path}"${l.external ? ' rel="noopener noreferrer"' : ''}>${escapeHtml(l.label)}</a>`)
    .join('\n        ')
  return `<footer class="site-footer no-print">
      <nav class="site-footer-links" aria-label="${attr(t(locale, 'static.footerSite'))}">
        ${links}
      </nav>
      <p class="site-footer-legal">© ${year} ${escapeHtml(OPERATOR)} · <a href="${LICENSE_URL}" rel="license noopener">${LICENSE_NAME}</a></p>
    </footer>`
}

function homeContent(route) {
  const { locale } = route
  const h = (key, params) => html(locale, key, params)
  const cards = localizedWorksheets(locale).map(ws => worksheetCard(ws, locale)).join('\n        ')
  return `<main class="catalog catalog--full static-page">
      <header class="catalog-header">
        <div class="catalog-brand">
          <h1 class="catalog-title">${brandIcon(28)}${BRAND} – ${escapeHtml(t(locale, 'site.tagline'))}</h1>
          <p class="catalog-subtitle">${h('static.home.subtitle')}</p>
        </div>
      </header>
      <section class="static-intro">
        <p>${h('static.home.intro1', { brand: BRAND })}</p>
        <p>${h('static.home.intro2')}</p>
      </section>
      <h2>${h('static.home.worksheets')}</h2>
      <nav class="catalog-grid" aria-label="${attr(t(locale, 'static.worksheetTypes'))}">
        ${cards}
      </nav>
      <h2>${h('static.home.howItWorks')}</h2>
      <ol>
        <li>${h('static.home.step1')}</li>
        <li>${h('static.home.step2')}</li>
        <li>${h('static.home.step3')}</li>
      </ol>
      <h2>${h('static.home.audienceHeading')}</h2>
      <p>${h('static.home.audienceText', { brand: BRAND })}</p>
      ${agentLinksHtml(locale)}
    </main>`
}

function worksheetContent(route) {
  const { locale } = route
  const h = (key, params) => html(locale, key, params)
  const ws = route.worksheet
  const others = localizedWorksheets(locale).filter(w => w.id !== ws.id)
  const settings = ws.settings.map(s => `<li>${escapeHtml(s)}</li>`).join('\n        ')
  const related = others.map(w => `<li><a href="${worksheetRoute(w, locale).path}">${escapeHtml(w.label)}</a> – ${escapeHtml(w.shortDesc)}</li>`).join('\n        ')
  return `<main class="catalog catalog--full static-page">
      ${breadcrumbNav(locale, ws.label)}
      <header class="catalog-header">
        <div class="catalog-brand">
          <h1 class="catalog-title">${h('seo.worksheetHeading', { label: ws.label })}</h1>
          <p class="catalog-subtitle">${escapeHtml(ws.shortDesc)} · ${escapeHtml(gradeLevelText(ws, locale))}</p>
        </div>
      </header>
      <section class="static-intro">
        <p>${escapeHtml(ws.longDesc)}</p>
        <p><strong>${h('static.worksheet.skills')}:</strong> ${ws.skills.map(escapeHtml).join(', ')}. <strong>${h('static.worksheet.format')}:</strong> ${h(ws.interactive ? 'static.worksheet.formatInteractive' : 'static.worksheet.formatPrintable')}.</p>
      </section>
      <h2>${h('static.worksheet.settings')}</h2>
      <ul>
        ${settings}
      </ul>
      <h2>${h(ws.interactive ? 'static.worksheet.howToUseActivity' : 'static.worksheet.howToUseWorksheet')}</h2>
      <ol>
        <li>${h('static.worksheet.step1', { url: link(route.path, absoluteUrl(route.path)) })}</li>
        <li>${h('static.worksheet.step2')}</li>
        <li>${h(ws.interactive ? 'static.worksheet.step3Interactive' : 'static.worksheet.step3Printable')}</li>
      </ol>
      <h2>${h('static.worksheet.others', { brand: BRAND })}</h2>
      <ul>
        ${related}
      </ul>
      ${agentLinksHtml(locale)}
    </main>`
}

function developersBody(route) {
  const { locale } = route
  const h = (key, params) => html(locale, key, params)
  const list = WORKSHEETS.map(w => {
    const r = worksheetRoute(w, locale)
    return `<li><code>${w.id}</code> → <a href="${r.path}">${r.path}</a> (<a href="${r.md}">.md</a>)</li>`
  }).join('\n        ')
  return `${breadcrumbNav(locale, t(locale, 'seo.developersCrumb'))}
      <header class="catalog-header">
        <div class="catalog-brand">
          <h1 class="catalog-title">${h('seo.developersHeading', { brand: BRAND })}</h1>
          <p class="catalog-subtitle">${h('static.developers.subtitle')}</p>
        </div>
      </header>
      <section class="static-intro">
        <p>${h('static.developers.intro', { brand: BRAND, brandAlt: t(locale, 'site.brandAlt') })}</p>
      </section>
      <h2>${h('static.developers.resources')}</h2>
      <ul>
        <li><a href="${GITHUB_URL}">${h('static.developers.sourceLink')}</a> – ${LICENSE_NAME}, <code>npm install &amp;&amp; npm run dev</code></li>
        <li><a href="/worksheets.json">worksheets.json</a> – ${h('static.developers.catalogDesc')}</li>
        <li><a href="/llms.txt">llms.txt</a>, <a href="/llms-full.txt">llms-full.txt</a> – ${h('static.developers.llmsDesc')}</li>
        <li><a href="/sitemap.xml">sitemap.xml</a>, <a href="/robots.txt">robots.txt</a></li>
        <li><a href="${homeRoute(locale).md}">${homeRoute(locale).mdFile}</a> – ${h('static.developers.indexMdDesc', { code: code('.md') })}</li>
      </ul>
      <h2>${h('static.developers.negotiationHeading')}</h2>
      <p>${h('static.developers.negotiationText', {
        accept: code('Accept: text/markdown'),
        contentType: code('Content-Type: text/markdown; charset=utf-8'),
        vary: code('Vary: Accept'),
        link: code('Link: rel="alternate"; type="text/markdown"'),
      })}</p>
      <h2>${h('static.developers.languagesHeading')}</h2>
      <p>${h('static.developers.languagesText', { languages: languageNames(), example: code(exampleLocalizedPath()) })}</p>
      <h2>${h('static.developers.idsHeading')}</h2>
      <ul>
        ${list}
      </ul>
      <h2>${h('static.developers.addingHeading')}</h2>
      <ol>
        <li>${h('static.developers.adding1', { file: code('src/worksheets.js'), messages: code('src/i18n/messages/<locale>.js') })}</li>
        <li>${h('static.developers.adding2', { dir: code('src/components/'), components: code('COMPONENTS'), icons: code('ICONS'), app: code('src/App.jsx') })}</li>
        <li>${h('static.developers.adding3', { test: code('npm test'), build: code('npm run build') })}</li>
      </ol>`
}

function formatDate(iso, locale = DEFAULT_LOCALE) {
  const d = new Date(`${iso}T00:00:00Z`)
  return d.toLocaleDateString(langOf(locale), { year: 'numeric', month: 'long', day: 'numeric', timeZone: 'UTC' })
}

function sectionHtml(section, locale) {
  const parts = [`<h2>${escapeHtml(section.heading)}</h2>`]
  for (const p of section.paragraphs || []) parts.push(`<p>${inlineHtml(p, locale)}</p>`)
  if (section.items?.length) {
    parts.push(`<ul>\n        ${section.items.map(i => `<li>${inlineHtml(i, locale)}</li>`).join('\n        ')}\n      </ul>`)
  }
  return parts.join('\n      ')
}

function pageBody(route) {
  const { locale, page } = route
  return `${breadcrumbNav(locale, page.navLabel)}
      <header class="catalog-header">
        <div class="catalog-brand">
          <h1 class="catalog-title">${escapeHtml(page.title)}</h1>
          <p class="catalog-subtitle">${html(locale, 'static.lastUpdated', { date: formatDate(page.updated, locale) })}</p>
        </div>
      </header>
      <section class="static-intro">
        <p>${inlineHtml(page.description, locale)}</p>
      </section>
      ${page.sections.map(s => sectionHtml(s, locale)).join('\n      ')}`
}

/**
 * Inner HTML of a non-worksheet page (developers, about, privacy, terms):
 * used inside <main class="catalog catalog--full static-page"> both by the
 * prerendered fallback and by the React StaticPage component.
 */
export function staticBody(route) {
  if (route.kind === 'developers') return developersBody(route)
  if (route.kind === 'page') return pageBody(route)
  throw new Error(`staticBody: no static body for route kind "${route.kind}"`)
}

function staticMain(route) {
  return `<main class="catalog catalog--full static-page">
      ${staticBody(route)}
    </main>`
}

export function renderStaticContent(route) {
  const inner =
    route.kind === 'home' ? homeContent(route) :
    route.kind === 'worksheet' ? worksheetContent(route) :
    staticMain(route)
  return `<div id="static-content">\n    ${inner}\n    ${footerHtml({ locale: route.locale })}\n    </div>`
}

/** Replace the marker blocks in an HTML template with this route's head and content, and set <html lang>. */
export function injectRoute(template, route) {
  const headRe = new RegExp(`${HEAD_START}[\\s\\S]*?${HEAD_END.replace('/', '\\/')}`)
  const contentRe = new RegExp(`${CONTENT_START}[\\s\\S]*?${CONTENT_END.replace('/', '\\/')}`)
  if (!headRe.test(template)) throw new Error('index.html is missing the <!-- seo:head --> … <!-- /seo:head --> markers')
  if (!contentRe.test(template)) throw new Error('index.html is missing the <!-- seo:content --> … <!-- /seo:content --> markers')
  return template
    .replace(/<html\b([^>]*)>/, (m, attrs) => `<html${attrs.replace(/\s+lang="[^"]*"/, '')} lang="${langOf(route.locale)}">`)
    .replace(headRe, () => `${HEAD_START}\n    ${renderHead(route)}\n    ${HEAD_END}`)
    .replace(contentRe, () => `${CONTENT_START}\n    ${renderStaticContent(route)}\n    ${CONTENT_END}`)
}

/* ────────────────────────────── Markdown ────────────────────────────── */

function mdLink(label, path) {
  return `[${label}](${absoluteUrl(path)})`
}

function agentLinksMarkdown(locale) {
  const m = (key, params) => text(locale, key, params)
  return [
    m('md.agentIntro'),
    ``,
    `- ${mdLink('llms.txt', '/llms.txt')}: ${m('md.llmsNote')}`,
    `- ${mdLink('worksheets.json', '/worksheets.json')}: ${m('md.catalogNote')}`,
    `- ${mdLink(m('md.developersLink'), developersRoute(locale).md)}`,
    `- ${mdLink(m('md.sitemapLink'), '/sitemap.xml')}`,
    `- [${m('md.sourceLink')}](${GITHUB_URL}): ${LICENSE_NAME}`,
  ].join('\n')
}

export function renderIndexMarkdown(route = homeRoute()) {
  const { locale } = route
  const m = (key, params) => text(locale, key, params)
  const list = localizedWorksheets(locale)
    .map(w => `- ${m('md.worksheetItem', { link: mdLink(w.label, worksheetRoute(w, locale).md), shortDesc: w.shortDesc, grades: w.grades })}`)
    .join('\n')
  return `# ${pageTitle(route)}

> ${m('site.description')}

${m('md.homeIntro', { brand: BRAND })}

## ${m('static.home.worksheets')}

${list}

## ${m('md.howItWorks')}

1. ${m('md.step1')}
2. ${m('md.step2')}
3. ${m('md.step3')}

## ${m('md.forDevelopers')}

${agentLinksMarkdown(locale)}
`
}

export function renderWorksheetMarkdown(route) {
  const { locale } = route
  const m = (key, params) => text(locale, key, params)
  const ws = route.worksheet
  const settings = ws.settings.map(s => `- ${s}`).join('\n')
  const others = localizedWorksheets(locale).filter(w => w.id !== ws.id)
    .map(w => `- ${mdLink(w.label, worksheetRoute(w, locale).md)}: ${w.shortDesc}`)
    .join('\n')
  return `# ${m('seo.worksheetHeading', { label: ws.label })}

> ${ws.shortDesc}. ${gradeLevelText(ws, locale)}. ${m('static.worksheet.partOf', { link: mdLink(BRAND, homeRoute(locale).md) })}

${ws.longDesc}

**${m('static.worksheet.skills')}:** ${ws.skills.join(', ')}.
**${m('static.worksheet.format')}:** ${m(ws.interactive ? 'static.worksheet.formatInteractive' : 'static.worksheet.formatPrintable')}.
**${m('static.worksheet.url')}:** ${absoluteUrl(route.path)}

## ${m('static.worksheet.settings')}

${settings}

## ${m('md.howToUse')}

1. ${m('md.wsStep1', { url: absoluteUrl(route.path) })}
2. ${m('md.wsStep2')}
3. ${m(ws.interactive ? 'static.worksheet.step3Interactive' : 'static.worksheet.step3Printable')}

## ${m('static.worksheet.others', { brand: BRAND })}

${others}

## ${m('md.forDevelopers')}

${agentLinksMarkdown(locale)}
`
}

export function renderDevelopersMarkdown(route = developersRoute()) {
  const { locale } = route
  const m = (key, params) => text(locale, key, params)
  const list = WORKSHEETS.map(w => {
    const r = worksheetRoute(w, locale)
    return `- \`${w.id}\` → ${absoluteUrl(r.path)} (${mdLink(m('md.markdownLink'), r.md)})`
  }).join('\n')
  const home = homeRoute(locale)
  return `# ${m('seo.developersHeading', { brand: BRAND })}

> ${m('md.developersIntro', { brand: BRAND, brandAlt: m('site.brandAlt') })}

## ${m('static.developers.resources')}

- [${m('static.developers.sourceLink')}](${GITHUB_URL}): ${LICENSE_NAME}; \`npm install && npm run dev\`
- ${mdLink('worksheets.json', '/worksheets.json')}: ${m('md.devCatalogNote')}
- ${mdLink('llms.txt', '/llms.txt')}: ${m('md.devLlmsNote')}
- ${mdLink('llms-full.txt', '/llms-full.txt')}: ${m('md.devLlmsFullNote')}
- ${mdLink('sitemap.xml', '/sitemap.xml')}, ${mdLink('robots.txt', '/robots.txt')}
- ${mdLink(home.mdFile, home.md)}: ${m('md.devIndexNote')}

## ${m('static.developers.negotiationHeading')}

${m('md.negotiationText')}

## ${m('static.developers.languagesHeading')}

${m('md.languagesText', { languages: languageNames(), example: `\`${exampleLocalizedPath()}\`` })}

## ${m('static.developers.idsHeading')}

${list}

## ${m('static.developers.addingHeading')}

1. ${m('md.adding1')}
2. ${m('md.adding2')}
3. ${m('md.adding3')}
`
}

function sectionMarkdown(section, locale) {
  const parts = [`## ${section.heading}`, '']
  for (const p of section.paragraphs || []) parts.push(inlineMarkdown(p, locale), '')
  if (section.items?.length) parts.push(...section.items.map(i => `- ${inlineMarkdown(i, locale)}`), '')
  return parts.join('\n').trimEnd()
}

export function renderPageMarkdown(route) {
  const { locale, page } = route
  const m = (key, params) => text(locale, key, params)
  const more = [
    { label: m('md.homeLink', { brand: BRAND }), md: homeRoute(locale).md },
    ...localizedPages(locale).filter(p => p.id !== page.id).map(p => ({ label: p.title, md: pageRoute(p, locale).md })),
  ].map(l => `- ${mdLink(l.label, l.md)}`).join('\n')
  return `# ${page.title}

> ${inlineMarkdown(page.description, locale)}

**${m('md.lastUpdated')}:** ${formatDate(page.updated, locale)}
**${m('static.worksheet.url')}:** ${absoluteUrl(route.path)}

${page.sections.map(s => sectionMarkdown(s, locale)).join('\n\n')}

## ${m('md.moreFrom', { brand: BRAND })}

${more}
`
}

export function renderMarkdown(route) {
  if (route.kind === 'home') return renderIndexMarkdown(route)
  if (route.kind === 'developers') return renderDevelopersMarkdown(route)
  if (route.kind === 'page') return renderPageMarkdown(route)
  return renderWorksheetMarkdown(route)
}

/* ────────────────────────────── llms.txt (English only) ────────────────────────────── */

export function renderLlmsTxt() {
  const pages = PAGES.map(p => `- ${mdLink(p.title, pageRoute(p).md)}: ${p.description}`).join('\n')
  const worksheets = WORKSHEETS.map(w => `- ${mdLink(w.label, worksheetRoute(w).md)}: ${w.shortDesc}; grades ${w.grades}; ${w.interactive ? 'interactive on-screen activity' : 'printable'}`).join('\n')
  const otherLocales = LOCALES.filter(l => l !== DEFAULT_LOCALE)
  const localized = otherLocales
    .map(l => `- ${mdLink(`Home page (${LOCALE_META[l].englishName})`, homeRoute(l).md)}: ${t(DEFAULT_LOCALE, 'llms.optionalLocale', { language: LOCALE_META[l].englishName })}`)
    .join('\n')
  return `# ${BRAND}

> ${BRAND} (“${t(DEFAULT_LOCALE, 'site.brandAlt')}”) is a free, open-source web app with printable, randomized math worksheets for grades 1–3: multiplication tables, addition and subtraction, column addition, long multiplication, comparison, rounding, number patterns, plus an interactive equation explorer. Site: ${SITE_URL}/

Worksheets are generated in the browser and printed from the print dialog; there is no account, no server API and no cost (${LICENSE_NAME}). Every HTML page has a Markdown twin: append \`.md\` to the path or request the page with \`Accept: text/markdown\`. Pages are also available in ${otherLocales.map(l => LOCALE_META[l].englishName).join(', ')} under a two-letter path prefix (for example \`${exampleLocalizedPath()}\`).

## Worksheets

${worksheets}

## Developers

- ${mdLink('Developer resources', '/developers.md')}: repository, catalog JSON, content negotiation, how to add a worksheet
- ${mdLink('Worksheet catalog (JSON)', '/worksheets.json')}: ids, slugs, URLs, grades, skills and settings for every worksheet
- [Source on GitHub](${GITHUB_URL}): React 19 + Vite, ${LICENSE_NAME}

## Optional

- ${mdLink('Home page (Markdown)', '/index.md')}: overview of the site
- ${mdLink('llms-full.txt', '/llms-full.txt')}: every page's Markdown concatenated in one file
- ${mdLink('Sitemap', '/sitemap.xml')}: all HTML URLs in every language
${pages}
${localized}
`
}

export function renderLlmsFullTxt() {
  const sections = routes(DEFAULT_LOCALE).map(r => renderMarkdown(r).trimEnd())
  return `${sections.join('\n\n---\n\n')}\n`
}

/* ────────────────────────────── sitemap / robots / catalog ────────────────────────────── */

export function renderSitemap({ now = new Date() } = {}) {
  const lastmod = now.toISOString().slice(0, 10)
  const urls = routes().map(r => {
    const priority = r.kind === 'home' ? '1.0' : r.kind === 'worksheet' ? '0.8' : r.kind === 'page' ? '0.3' : '0.5'
    const alternates = [
      ...LOCALES.map(l => `    <xhtml:link rel="alternate" hreflang="${LOCALE_META[l].hreflang}" href="${escapeHtml(absoluteUrl(sameRouteIn(r, l).path))}" />`),
      `    <xhtml:link rel="alternate" hreflang="x-default" href="${escapeHtml(absoluteUrl(sameRouteIn(r, DEFAULT_LOCALE).path))}" />`,
    ].join('\n')
    return `  <url>
    <loc>${escapeHtml(absoluteUrl(r.path))}</loc>
    <lastmod>${lastmod}</lastmod>
    <changefreq>monthly</changefreq>
    <priority>${priority}</priority>
${alternates}
  </url>`
  })
  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">
${urls.join('\n')}
</urlset>
`
}

export const AI_CRAWLERS = [
  'GPTBot', 'OAI-SearchBot', 'ChatGPT-User', 'ClaudeBot', 'Claude-Web', 'Claude-SearchBot', 'anthropic-ai',
  'PerplexityBot', 'Perplexity-User', 'Google-Extended', 'Applebot-Extended', 'CCBot', 'Bytespider', 'Amazonbot', 'meta-externalagent',
]

export function renderRobots() {
  const blocks = AI_CRAWLERS.map(ua => `User-agent: ${ua}\nAllow: /`).join('\n\n')
  return `# ${BRAND} – ${SITE_URL}/
# Everything is public. AI crawlers and answer engines are welcome; see /llms.txt.

User-agent: *
Allow: /

${blocks}

Sitemap: ${absoluteUrl('/sitemap.xml')}
`
}

export function catalogJson({ now = new Date() } = {}) {
  return {
    name: BRAND,
    alternateName: t(DEFAULT_LOCALE, 'site.brandAlt'),
    description: t(DEFAULT_LOCALE, 'site.description'),
    url: `${SITE_URL}/`,
    generatedAt: now.toISOString(),
    license: { name: LICENSE_NAME, url: LICENSE_URL },
    repository: GITHUB_URL,
    llms: absoluteUrl('/llms.txt'),
    sitemap: absoluteUrl('/sitemap.xml'),
    developers: absoluteUrl('/developers'),
    pages: Object.fromEntries(PAGES.map(p => [p.id, absoluteUrl(pageRoute(p).path)])),
    locales: LOCALES.map(l => ({ code: l, lang: LOCALE_META[l].lang, name: LOCALE_META[l].englishName, url: absoluteUrl(homeRoute(l).path) })),
    worksheets: WORKSHEETS.map(w => {
      const r = worksheetRoute(w)
      return {
        id: w.id,
        slug: w.slug,
        label: w.label,
        url: absoluteUrl(r.path),
        markdownUrl: absoluteUrl(r.md),
        alternates: Object.fromEntries(LOCALES.map(l => [l, absoluteUrl(worksheetRoute(w, l).path)])),
        description: w.shortDesc,
        longDescription: w.longDesc,
        grades: w.grades,
        skills: w.skills,
        settings: w.settings,
        printable: !w.interactive,
        interactive: w.interactive,
      }
    }),
  }
}

export function renderCatalogJson(opts) {
  return `${JSON.stringify(catalogJson(opts), null, 2)}\n`
}

/* ────────────────────────────── 404 ────────────────────────────── */

function notFoundLinks(locale) {
  return [
    { label: t(locale, 'notFound.home', { brand: BRAND }), path: homeRoute(locale).path },
    ...localizedWorksheets(locale).map(w => ({ label: t(locale, 'notFound.worksheet', { label: w.label }), path: worksheetRoute(w, locale).path })),
    { label: t(locale, 'notFound.developers'), path: developersRoute(locale).path },
    ...localizedPages(locale).map(p => ({ label: p.title, path: pageRoute(p, locale).path })),
    { label: t(locale, 'notFound.sitemap'), path: '/sitemap.xml' },
    { label: t(locale, 'notFound.llms'), path: '/llms.txt' },
    { label: t(locale, 'notFound.catalog'), path: '/worksheets.json' },
  ]
}

export function renderNotFoundMarkdown(pathname = '', locale = DEFAULT_LOCALE) {
  const m = (key, params) => text(locale, key, params)
  const shown = pathname ? `\`${pathname.replace(/`/g, '')}\` ` : ''
  const links = notFoundLinks(locale).map(l => `- ${mdLink(l.label, l.path)}`).join('\n')
  return `# ${m('notFound.title')} · ${BRAND}

${m('notFound.body', { path: shown, site: SITE_URL })}

## ${m('notFound.whereNext')}

${links}

${m('notFound.twinMd')}
`
}

export function renderNotFoundHtml(pathname = '', locale = DEFAULT_LOCALE) {
  const h = (key, params) => html(locale, key, params)
  const links = notFoundLinks(locale).map(l => `<li><a href="${l.path}">${escapeHtml(l.label)}</a></li>`).join('\n        ')
  const shown = pathname ? raw(`<code>${escapeHtml(pathname)}</code> `) : ''
  return `<!doctype html>
<html lang="${langOf(locale)}">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="robots" content="noindex" />
    <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
    <title>${h('notFound.title')} · ${BRAND}</title>
    <style>
      body { margin: 0; padding: 48px 20px; font-family: Inter, system-ui, -apple-system, "Segoe UI", sans-serif; color: #1f2937; background: #f8fafc; }
      main { max-width: 640px; margin: 0 auto; }
      h1 { font-size: 26px; margin: 0 0 8px; }
      h2 { font-size: 18px; margin: 28px 0 8px; }
      a { color: ${THEME_COLOR}; }
      code { background: #e5e7eb; padding: 1px 5px; border-radius: 4px; }
      ul { padding-left: 20px; line-height: 1.7; }
    </style>
  </head>
  <body>
    <main>
      <h1>${h('notFound.title')}</h1>
      <p>${h('notFound.body', { path: shown, site: BRAND })}</p>
      <h2>${h('notFound.whereNext')}</h2>
      <ul>
        ${links}
      </ul>
      <p>${h('notFound.twinHtml', { code: code('.md'), accept: code('Accept: text/markdown') })}</p>
    </main>
  </body>
</html>
`
}

/* ────────────────────────────── build output ────────────────────────────── */

/**
 * Everything the prerender step writes into dist/, keyed by relative path.
 * @param {string} template  the built dist/index.html
 */
export function buildSiteFiles(template, { now = new Date() } = {}) {
  const files = {}
  for (const route of routes()) {
    files[route.html] = injectRoute(template, route)
    files[route.mdFile] = renderMarkdown(route)
  }
  files['llms.txt'] = renderLlmsTxt()
  files['llms-full.txt'] = renderLlmsFullTxt()
  files['sitemap.xml'] = renderSitemap({ now })
  files['robots.txt'] = renderRobots()
  files['worksheets.json'] = renderCatalogJson({ now })
  files['404.html'] = renderNotFoundHtml()
  return files
}
